lang: fr

project:
  type: book

book:
  site-url: "https://howto.nicolasbressoud.ch"
  title: "Principes, procédures et tips pour traiter les données dans R"
  author:
    - PHilippe Gay
    - Nicolas Bressoud
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd
    - 01_environnement.qmd
    - 02_preparation.qmd
    - 03_description.qmd
    - 04_rapport.qmd
    - 05_etudes_de_cas.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



